First pass at swapping out hubspot client for sendgrid client
THIS-Institute/thiscovery-crm pull request #33
Opened 2023-03-06 16:06 UTC by alistairclark

2023-03-06 16:06 UTC, this-andy commented
https://this.tpondemand.com/entity/4862

2023-03-13 15:57 UTC, this-andy requested changes
Alistair, it may be useful to discuss some of my comments.  Some could be erroneous due to my lack of knowledge of SendGrid.

2023-03-13 15:57 UTC, this-andy commented on README.md
>  2. Dynamodb "lookups" table (stores configuration)
Both lookups and tokens tables hold HubSpot specific data.  Both can be deleted once HubSpot is no longer used

2023-03-13 15:57 UTC, this-andy commented on requirements.txt
> +https://github.com/THIS-Institute/thiscovery-lib/archive/refs/heads/alistair-us-4862-sendgrid-setup.zip
Why the developer specific file here?  Will this be replaced later?

2023-03-13 15:57 UTC, this-andy commented on admin_tasks/add_email_template_to_dynamodb.py
> +        table_name="EmailTemplates",
Should this use TEMPLATES_TABLE constant?

2023-03-13 15:57 UTC, this-andy commented on src/requirements.txt
> +https://github.com/THIS-Institute/thiscovery-lib/archive/refs/heads/alistair-us-4862-sendgrid-setup.zip
As per previous comment re developer specific file

2023-03-13 15:57 UTC, this-andy commented on src/transactional_email.py
> +    templates_table = "EmailTemplates"
Use existing constant?

2023-03-13 15:57 UTC, this-andy commented on src/transactional_email.py
> +    def __init__(self, email_dict, correlation_id=None):
Does SG not support a 'send-id' - basically some sort of client supplied id that can be used later to refer to email requests.  Or does it have a different approach?

2023-03-14 11:42 UTC, alistairclark commented on requirements.txt
> +https://github.com/THIS-Institute/thiscovery-lib/archive/refs/heads/alistair-us-4862-sendgrid-setup.zip
For now it's pointing at this branch because that's the only place where SendgridClient exists, can revert back to using master once the other PR is merged!

2023-03-14 14:24 UTC, alistairclark commented on src/transactional_email.py
> +    def __init__(self, email_dict, correlation_id=None):
Have had a good look and it doesn't seem there is any support for this. Potentially could implement something our side for checking this, but I guess the notification processing system in theory is designed to handle this. Based on how it actually works though I'm not sure if it is 100% safe to assume it wouldn't send multiple. Can discuss in the next dev meeting.

2023-03-15 12:57 UTC, sophiemachin commented on test_email.py
> +
Is this test meant to be inside tests/unit_tests? 

If it is you'll need the try/except around the secrets and dev_config imports for it to run on CICD

2023-03-15 12:59 UTC, sophiemachin commented on test_email.py
> +
Oh i see this is a copy of the stuff you have in the lib PR

2023-03-15 13:26 UTC, sophiemachin commented on src/notification_process.py
> -def process_test(notification):
This function is referenced on line 265, should that be removed?

2023-03-15 13:35 UTC, sophiemachin commented on src/notification_process.py
> +        if notification_type == NotificationType.TRANSACTIONAL_EMAIL.value:
`signup_notifications = list()` and `login_notifications = list()`  are now unused

2023-03-15 13:35 UTC, sophiemachin commented on src/notification_process.py
>          elif notification_type == NotificationType.PROCESSING_TEST.value:
I think this is also redundant

2023-03-17 12:26 UTC, this-andy requested changes

2023-03-17 12:26 UTC, this-andy commented on template.yaml
> +            TableName: !Ref EmailTemplates
Suggest you leave HubSpot email templates there for the moment (but unused) for reference in case we have forgotten to migrate any templates.
Then we can remove later once we are happy with everything

2023-03-17 12:26 UTC, this-andy commented on template.yaml
> +  EmailTemplates:
As above - leave HS templates table in place for now

2023-03-31 10:47 UTC, alistairclark commented on tests/unit_tests/test_transactional_email.py
> +        mocked_response.status_code = 200
Should be 202

2023-03-31 10:47 UTC, alistairclark commented on tests/unit_tests/test_transactional_email.py
>          self.assertEqual(HTTPStatus.OK, response.status_code)
Should be `HttpStatus.ACCEPTED`

2023-03-31 10:57 UTC, alistairclark commented on test_email.py
> +t.send()
Delete this file

2023-03-31 10:59 UTC, alistairclark commented on tests/unit_tests/test_transactional_email.py
> +        mocked_response.status_code = 200
And all occurrences in this file

2023-04-12 10:25 UTC, closed without merging